name: 'build-macos'
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false
  
jobs:
  build-macos:
    runs-on: macos-15
    # macos-latest
    steps:
      - name: Set up git repo
        uses: actions/checkout@v5
        
      - name: Checkout submodules
        run: git submodule update --init --recursive
        
      - name: Cache ~/pp
        uses: actions/cache@v4
        with:
          path: ~/pp
          key: ${{ runner.os }}-${{ matrix.ghc }}-pp

      - name: Cache ./pp
        uses: actions/cache@v4
        with:
          path: ./pp
          key: ${{ runner.os }}-${{ matrix.ghc }}-pp
          
      - name: Cache ~/.cabal/packages
        uses: actions/cache@v4
        with:
          path: ~/.cabal/packages
          key: ${{ runner.os }}-${{ matrix.ghc }}-cabal-packages

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.4.5' # Not needed with a .ruby-version file
          # bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          cache-version: 2 # Increment this number if you need to re-download cached gems

      - run: bundle install
      
      - name: Install deps
        run: brew install haskell-stack cabal-install agda pandoc pandoc-crossref gsed
        # deprecated: pandoc-citeproc

      - run: cp -R .agda ~/

      - run: ls -la ~/.agda/
      #- run: cat ~/.adga/defaults
      #- run: cat ~/.agda/libraries
        
      - name: Install pandoc-numbering
        run: pip3 install pandoc-numbering --break-system-packages
      # gem install ffi -v '1.15.5' -- --with-cflags=-Wno-implicit-function-declaration
      
      - name: Update cabal
        run: cabal update
        
      - name: Make pp
        run: cd pp && make

      - name: Copy pp
        run: cd pp && cp "$(stack path --local-install-root)/bin/pp" ./pp-macos
        
      # - name: Ls
      #   run: ls -la pp/src/
        
#      - name: Install pp
#        run: cd pp && make  install

      # - name: install latest Agda
      #   run: cabal install Agda --overwrite-policy=always

      - name: std-lib
        run: cd agda-stdlib && cabal install --overwrite-policy=always

      # - name: Build the book 1
        # run: make agda; make agda
        
      - name: Build the book
        run: make
          
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        # Automatically uploads an artifact from the './_site' directory by default
        uses: actions/upload-pages-artifact@v3
        
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build-macos
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
